### ISSUE TITLE
Please add info about people behind Revel.

### ISSUE THREAD

**Issue by urza** [revel/revel.github.io#80]
Hi
I would like to know more about people behind Revel. Who is doing it, what is their motivation. What guarantee I have that this project will be kept alive in future (is it backed by some company? What if authors will get new job? Or family? etc) Will there be support? generally I would like to evaluate not just by features but also by stability-maturity of the team behind it.

So the issue: please add some info to the website, that addresses my above questions.

Thanks

**Comment by DavidHunter** [comment]
You can join the team to make sure it stays alive. We currently need more contributors

**Comment by levilovelock** [comment]
Also, in case you've not seen it - we currently list the core members, so you could technically stalk them from there if you saw fit ;)

https://github.com/revel/revel/wiki/Core-Team

**Comment by brendensoares** [comment]
@urza interesting request, but before we can spend effort on polishing our web presence and story, we need to polish our framework. We have a roadmap and it is a challenge to continue progress because all core team members are simply volunteers with no obligation to continue work except out of personal interest.

As @DavidHunter said, we need strong contributors and one way you can ensure Revel's long term future is to participate. It is open source software after all. :)
